name: deploy
on:
  push:
    branches:
      - main
jobs:
  deploy-to-prod:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
        ref: 'main'
    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        known_hosts: ${{ secrets.SSH_HOST }}
    - name: Push remote
      run: |
        git config user.name "davvalent"
        git config user.email "d@ntnlv.ca"
        git remote add prod ${{ secrets.SSH_TARGET }}
        git add .
        git commit --allow-empty -am "deploy from Github CI/CD"
        git push -f prod main